site_name: DORIS Homepage

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: bottom
    navigation_depth: 4
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search

markdown_extensions:
  - footnotes

nav:
    - DORIS:
        - General Information: 'index.md'
        - Mortality digital end-to-end solution: 'icd11mde2e.md'
        - Release Notes: 'release-notes.md'
    - Web Version: 
        - Doris Web: 'doris-web.md'
    - Desktop version: 
        - DORIS UI: 'doris-ui.md'
    - Using DORIS from other software: 
        - Using DORIS from ICD-API: 'doris-api.md'
